const data = [
  {
    id: 1,
    name: "Andhra Pradesh",
    districts: [
      { id: 1, name: "Anantapur", state_id: 1 },
      { id: 2, name: "Chittoor", state_id: 1 },
      { id: 3, name: "East Godavari", state_id: 1 },
      { id: 4, name: "Guntur", state_id: 1 },
      { id: 5, name: "Krishna", state_id: 1 },
      { id: 6, name: "Kurnool", state_id: 1 },
      { id: 7, name: "Prakasam", state_id: 1 },
      { id: 8, name: "Srikakulam", state_id: 1 },
      { id: 9, name: "Sri Potti Sriramulu Nellore", state_id: 1 },
      { id: 10, name: "Visakhapatnam", state_id: 1 },
      { id: 11, name: "Vizianagaram", state_id: 1 },
      { id: 12, name: "West Godavari", state_id: 1 },
      { id: 13, name: "YSR District, Kadapa (Cuddapah)", state_id: 1 },
    ],
  },
  {
    id: 2,
    name: "Arunachal Pradesh",
    districts: [
      { id: 14, name: "Anjaw", state_id: 2 },
      { id: 15, name: "Changlang", state_id: 2 },
      { id: 16, name: "Dibang Valley", state_id: 2 },
      { id: 17, name: "East Kameng", state_id: 2 },
      { id: 18, name: "East Siang", state_id: 2 },
      { id: 19, name: "Kra Daadi", state_id: 2 },
      { id: 20, name: "Kurung Kumey", state_id: 2 },
      { id: 21, name: "Lohit", state_id: 2 },
      { id: 22, name: "Longding", state_id: 2 },
      { id: 23, name: "Lower Dibang Valley", state_id: 2 },
      { id: 24, name: "Lower Siang", state_id: 2 },
      { id: 25, name: "Lower Subansiri", state_id: 2 },
      { id: 26, name: "Namsai", state_id: 2 },
      { id: 27, name: "Papum Pare", state_id: 2 },
      { id: 28, name: "Siang", state_id: 2 },
      { id: 29, name: "Tawang", state_id: 2 },
      { id: 30, name: "Tirap", state_id: 2 },
      { id: 31, name: "Upper Siang", state_id: 2 },
      { id: 32, name: "Upper Subansiri", state_id: 2 },
      { id: 33, name: "West Kameng", state_id: 2 },
      { id: 34, name: "West Siang", state_id: 2 },
    ],
  },
  {
    id: 3,
    name: "Assam",
    districts: [
      { id: 35, name: "Baksa", state_id: 3 },
      { id: 36, name: "Barpeta", state_id: 3 },
      { id: 37, name: "Biswanath", state_id: 3 },
      { id: 38, name: "Bongaigaon", state_id: 3 },
      { id: 39, name: "Cachar", state_id: 3 },
      { id: 40, name: "Charaideo", state_id: 3 },
      { id: 41, name: "Chirang", state_id: 3 },
      { id: 42, name: "Darrang", state_id: 3 },
      { id: 43, name: "Dhemaji", state_id: 3 },
      { id: 44, name: "Dhubri", state_id: 3 },
      { id: 45, name: "Dibrugarh", state_id: 3 },
      { id: 46, name: "Dima Hasao (North Cachar Hills)", state_id: 3 },
      { id: 47, name: "Goalpara", state_id: 3 },
      { id: 48, name: "Golaghat", state_id: 3 },
      { id: 49, name: "Hailakandi", state_id: 3 },
      { id: 50, name: "Hojai", state_id: 3 },
      { id: 51, name: "Jorhat", state_id: 3 },
      { id: 52, name: "Kamrup", state_id: 3 },
      { id: 53, name: "Kamrup Metropolitan", state_id: 3 },
      { id: 54, name: "Karbi Anglong", state_id: 3 },
      { id: 55, name: "Karimganj", state_id: 3 },
      { id: 56, name: "Kokrajhar", state_id: 3 },
      { id: 57, name: "Lakhimpur", state_id: 3 },
      { id: 58, name: "Majuli", state_id: 3 },
      { id: 59, name: "Morigaon", state_id: 3 },
      { id: 60, name: "Nagaon", state_id: 3 },
      { id: 61, name: "Nalbari", state_id: 3 },
      { id: 62, name: "Sivasagar", state_id: 3 },
      { id: 63, name: "Sonitpur", state_id: 3 },
      { id: 64, name: "South Salamara-Mankachar", state_id: 3 },
      { id: 65, name: "Tinsukia", state_id: 3 },
      { id: 66, name: "Udalguri", state_id: 3 },
      { id: 67, name: "West Karbi Anglong", state_id: 3 },
    ],
  },
  {
    id: 4,
    name: "Bihar",
    districts: [
      { id: 68, name: "Araria", state_id: 4 },
      { id: 69, name: "Arwal", state_id: 4 },
      { id: 70, name: "Aurangabad", state_id: 4 },
      { id: 71, name: "Banka", state_id: 4 },
      { id: 72, name: "Begusarai", state_id: 4 },
      { id: 73, name: "Bhagalpur", state_id: 4 },
      { id: 74, name: "Bhojpur", state_id: 4 },
      { id: 75, name: "Buxar", state_id: 4 },
      { id: 76, name: "Darbhanga", state_id: 4 },
      { id: 77, name: "East Champaran (Motihari)", state_id: 4 },
      { id: 78, name: "Gaya", state_id: 4 },
      { id: 79, name: "Gopalganj", state_id: 4 },
      { id: 80, name: "Jamui", state_id: 4 },
      { id: 81, name: "Jehanabad", state_id: 4 },
      { id: 82, name: "Kaimur (Bhabua)", state_id: 4 },
      { id: 83, name: "Katihar", state_id: 4 },
      { id: 84, name: "Khagaria", state_id: 4 },
      { id: 85, name: "Kishanganj", state_id: 4 },
      { id: 86, name: "Lakhisarai", state_id: 4 },
      { id: 87, name: "Madhepura", state_id: 4 },
      { id: 88, name: "Madhubani", state_id: 4 },
      { id: 89, name: "Munger (Monghyr)", state_id: 4 },
      { id: 90, name: "Muzaffarpur", state_id: 4 },
      { id: 91, name: "Nalanda", state_id: 4 },
      { id: 92, name: "Nawada", state_id: 4 },
      { id: 93, name: "Patna", state_id: 4 },
      { id: 94, name: "Purnia (Purnea)", state_id: 4 },
      { id: 95, name: "Rohtas", state_id: 4 },
      { id: 96, name: "Saharsa", state_id: 4 },
      { id: 97, name: "Samastipur", state_id: 4 },
      { id: 98, name: "Saran", state_id: 4 },
      { id: 99, name: "Sheikhpura", state_id: 4 },
      { id: 100, name: "Sheohar", state_id: 4 },
      { id: 101, name: "Sitamarhi", state_id: 4 },
      { id: 102, name: "Siwan", state_id: 4 },
      { id: 103, name: "Supaul", state_id: 4 },
      { id: 104, name: "Vaishali", state_id: 4 },
      { id: 105, name: "West Champaran", state_id: 4 },
    ],
  },
  {
    id: 5,
    name: "Chhattisgarh",
    districts: [
      { id: 106, name: "Balod", state_id: 5 },
      { id: 107, name: "Baloda Bazar", state_id: 5 },
      { id: 108, name: "Balrampur", state_id: 5 },
      { id: 109, name: "Bastar", state_id: 5 },
      { id: 110, name: "Bemetara", state_id: 5 },
      { id: 111, name: "Bijapur", state_id: 5 },
      { id: 112, name: "Bilaspur", state_id: 5 },
      { id: 113, name: "Dantewada (South Bastar)", state_id: 5 },
      { id: 114, name: "Dhamtari", state_id: 5 },
      { id: 115, name: "Durg", state_id: 5 },
      { id: 116, name: "Gariyaband", state_id: 5 },
      { id: 117, name: "Janjgir-Champa", state_id: 5 },
      { id: 118, name: "Jashpur", state_id: 5 },
      { id: 119, name: "Kabirdham (Kawardha)", state_id: 5 },
      { id: 120, name: "Kanker (North Bastar)", state_id: 5 },
      { id: 121, name: "Kondagaon", state_id: 5 },
      { id: 122, name: "Korba", state_id: 5 },
      { id: 123, name: "Korea (Koriya)", state_id: 5 },
      { id: 124, name: "Mahasamund", state_id: 5 },
      { id: 125, name: "Mungeli", state_id: 5 },
      { id: 126, name: "Narayanpur", state_id: 5 },
      { id: 127, name: "Raigarh", state_id: 5 },
      { id: 128, name: "Raipur", state_id: 5 },
      { id: 129, name: "Rajnandgaon", state_id: 5 },
      { id: 130, name: "Sukma", state_id: 5 },
      { id: 131, name: "Surajpur ", state_id: 5 },
      { id: 132, name: "Surguja", state_id: 5 },
    ],
  },
  {
    id: 6,
    name: "Goa",
    districts: [
      { id: 133, name: "North Goa", state_id: 6 },
      { id: 134, name: "South Goa", state_id: 6 },
    ],
  },
  {
    id: 7,
    name: "Gujarat",
    districts: [
      { id: 135, name: "Ahmedabad", state_id: 7 },
      { id: 136, name: "Amreli", state_id: 7 },
      { id: 137, name: "Anand", state_id: 7 },
      { id: 138, name: "Aravalli", state_id: 7 },
      { id: 139, name: "Banaskantha (Palanpur)", state_id: 7 },
      { id: 140, name: "Bharuch", state_id: 7 },
      { id: 141, name: "Bhavnagar", state_id: 7 },
      { id: 142, name: "Botad", state_id: 7 },
      { id: 143, name: "Chhota Udepur", state_id: 7 },
      { id: 144, name: "Dahod", state_id: 7 },
      { id: 145, name: "Dangs (Ahwa)", state_id: 7 },
      { id: 146, name: "Devbhoomi Dwarka", state_id: 7 },
      { id: 147, name: "Gandhinagar", state_id: 7 },
      { id: 148, name: "Gir Somnath", state_id: 7 },
      { id: 149, name: "Jamnagar", state_id: 7 },
      { id: 150, name: "Junagadh", state_id: 7 },
      { id: 151, name: "Kachchh", state_id: 7 },
      { id: 152, name: "Kheda (Nadiad)", state_id: 7 },
      { id: 153, name: "Mahisagar", state_id: 7 },
      { id: 154, name: "Mehsana", state_id: 7 },
      { id: 155, name: "Morbi", state_id: 7 },
      { id: 156, name: "Narmada (Rajpipla)", state_id: 7 },
      { id: 157, name: "Navsari", state_id: 7 },
      { id: 158, name: "Panchmahal (Godhra)", state_id: 7 },
      { id: 159, name: "Patan", state_id: 7 },
      { id: 160, name: "Porbandar", state_id: 7 },
      { id: 161, name: "Rajkot", state_id: 7 },
      { id: 162, name: "Sabarkantha (Himmatnagar)", state_id: 7 },
      { id: 163, name: "Surat", state_id: 7 },
      { id: 164, name: "Surendranagar", state_id: 7 },
      { id: 165, name: "Tapi (Vyara)", state_id: 7 },
      { id: 166, name: "Vadodara", state_id: 7 },
      { id: 167, name: "Valsad", state_id: 7 },
    ],
  },
  {
    id: 8,
    name: "Haryana",
    districts: [
      { id: 168, name: "Ambala", state_id: 8 },
      { id: 169, name: "Bhiwani", state_id: 8 },
      { id: 170, name: "Charkhi Dadri", state_id: 8 },
      { id: 171, name: "Faridabad", state_id: 8 },
      { id: 172, name: "Fatehabad", state_id: 8 },
      { id: 173, name: "Gurgaon", state_id: 8 },
      { id: 174, name: "Hisar", state_id: 8 },
      { id: 175, name: "Jhajjar", state_id: 8 },
      { id: 176, name: "Jind", state_id: 8 },
      { id: 177, name: "Kaithal", state_id: 8 },
      { id: 178, name: "Karnal", state_id: 8 },
      { id: 179, name: "Kurukshetra", state_id: 8 },
      { id: 180, name: "Mahendragarh", state_id: 8 },
      { id: 181, name: "Mewat", state_id: 8 },
      { id: 182, name: "Palwal", state_id: 8 },
      { id: 183, name: "Panchkula", state_id: 8 },
      { id: 184, name: "Panipat", state_id: 8 },
      { id: 185, name: "Rewari", state_id: 8 },
      { id: 186, name: "Rohtak", state_id: 8 },
      { id: 187, name: "Sirsa", state_id: 8 },
      { id: 188, name: "Sonipat", state_id: 8 },
      { id: 189, name: "Yamunanagar", state_id: 8 },
    ],
  },
  {
    id: 9,
    name: "Himachal Pradesh",
    districts: [
      { id: 190, name: "Bilaspur", state_id: 9 },
      { id: 191, name: "Chamba", state_id: 9 },
      { id: 192, name: "Hamirpur", state_id: 9 },
      { id: 193, name: "Kangra", state_id: 9 },
      { id: 194, name: "Kinnaur", state_id: 9 },
      { id: 195, name: "Kullu", state_id: 9 },
      { id: 196, name: "Lahaul & Spiti", state_id: 9 },
      { id: 197, name: "Mandi", state_id: 9 },
      { id: 198, name: "Shimla", state_id: 9 },
      { id: 199, name: "Sirmaur (Sirmour)", state_id: 9 },
      { id: 200, name: "Solan", state_id: 9 },
      { id: 201, name: "Una", state_id: 9 },
    ],
  },
  {
    id: 10,
    name: "Jammu and Kashmir",
    districts: [
      { id: 202, name: "Anantnag", state_id: 10 },
      { id: 203, name: "Bandipore", state_id: 10 },
      { id: 204, name: "Baramulla", state_id: 10 },
      { id: 205, name: "Budgam", state_id: 10 },
      { id: 206, name: "Doda", state_id: 10 },
      { id: 207, name: "Ganderbal", state_id: 10 },
      { id: 208, name: "Jammu", state_id: 10 },
      { id: 209, name: "Kargil", state_id: 10 },
      { id: 210, name: "Kathua", state_id: 10 },
      { id: 211, name: "Kishtwar", state_id: 10 },
      { id: 212, name: "Kulgam", state_id: 10 },
      { id: 213, name: "Kupwara", state_id: 10 },
      { id: 214, name: "Leh", state_id: 10 },
      { id: 215, name: "Poonch", state_id: 10 },
      { id: 216, name: "Pulwama", state_id: 10 },
      { id: 217, name: "Rajouri", state_id: 10 },
      { id: 218, name: "Ramban", state_id: 10 },
      { id: 219, name: "Reasi", state_id: 10 },
      { id: 220, name: "Samba", state_id: 10 },
      { id: 221, name: "Shopian", state_id: 10 },
      { id: 222, name: "Srinagar", state_id: 10 },
      { id: 223, name: "Udhampur", state_id: 10 },
    ],
  },
  {
    id: 11,
    name: "Jharkhand",
    districts: [
      { id: 224, name: "Bokaro", state_id: 11 },
      { id: 225, name: "Chatra", state_id: 11 },
      { id: 226, name: "Deoghar", state_id: 11 },
      { id: 227, name: "Dhanbad", state_id: 11 },
      { id: 228, name: "Dumka", state_id: 11 },
      { id: 229, name: "East Singhbhum", state_id: 11 },
      { id: 230, name: "Garhwa", state_id: 11 },
      { id: 231, name: "Giridih", state_id: 11 },
      { id: 232, name: "Godda", state_id: 11 },
      { id: 233, name: "Gumla", state_id: 11 },
      { id: 234, name: "Hazaribag", state_id: 11 },
      { id: 235, name: "Jamtara", state_id: 11 },
      { id: 236, name: "Khunti", state_id: 11 },
      { id: 237, name: "Koderma", state_id: 11 },
      { id: 238, name: "Latehar", state_id: 11 },
      { id: 239, name: "Lohardaga", state_id: 11 },
      { id: 240, name: "Pakur", state_id: 11 },
      { id: 241, name: "Palamu", state_id: 11 },
      { id: 242, name: "Ramgarh", state_id: 11 },
      { id: 243, name: "Ranchi", state_id: 11 },
      { id: 244, name: "Sahibganj", state_id: 11 },
      { id: 245, name: "Seraikela-Kharsawan", state_id: 11 },
      { id: 246, name: "Simdega", state_id: 11 },
      { id: 247, name: "West Singhbhum", state_id: 11 },
    ],
  },
  {
    id: 12,
    name: "Karnataka",
    districts: [
      { id: 248, name: "Bagalkot", state_id: 12 },
      { id: 249, name: "Ballari (Bellary)", state_id: 12 },
      { id: 250, name: "Belagavi (Belgaum)", state_id: 12 },
      { id: 251, name: "Bengaluru (Bangalore) Rural", state_id: 12 },
      { id: 252, name: "Bengaluru (Bangalore) Urban", state_id: 12 },
      { id: 253, name: "Bidar", state_id: 12 },
      { id: 254, name: "Chamarajanagar", state_id: 12 },
      { id: 255, name: "Chikballapur", state_id: 12 },
      { id: 256, name: "Chikkamagaluru (Chikmagalur)", state_id: 12 },
      { id: 257, name: "Chitradurga", state_id: 12 },
      { id: 258, name: "Dakshina Kannada", state_id: 12 },
      { id: 259, name: "Davangere", state_id: 12 },
      { id: 260, name: "Dharwad", state_id: 12 },
      { id: 261, name: "Gadag", state_id: 12 },
      { id: 262, name: "Hassan", state_id: 12 },
      { id: 263, name: "Haveri", state_id: 12 },
      { id: 264, name: "Kalaburagi (Gulbarga)", state_id: 12 },
      { id: 265, name: "Kodagu", state_id: 12 },
      { id: 266, name: "Kolar", state_id: 12 },
      { id: 267, name: "Koppal", state_id: 12 },
      { id: 268, name: "Mandya", state_id: 12 },
      { id: 269, name: "Mysuru (Mysore)", state_id: 12 },
      { id: 270, name: "Raichur", state_id: 12 },
      { id: 271, name: "Ramanagara", state_id: 12 },
      { id: 272, name: "Shivamogga (Shimoga)", state_id: 12 },
      { id: 273, name: "Tumakuru (Tumkur)", state_id: 12 },
      { id: 274, name: "Udupi", state_id: 12 },
      { id: 275, name: "Uttara Kannada (Karwar)", state_id: 12 },
      { id: 276, name: "Vijayapura (Bijapur)", state_id: 12 },
      { id: 277, name: "Yadgir", state_id: 12 },
    ],
  },
  {
    id: 13,
    name: "Kerala",
    districts: [
      {
        id: 278,
        name: "Alappuzha",
        state_id: 13,
        children: [
          {
            value: "Chenganoor",
            label: "Chenganoor",
          },
          {
            value: "Mavelikkara",
            label: "Mavelikkara",
          },
          {
            value: "Karthikappally",
            label: "Karthikappally",
          },
          {
            value: "Kuttanad",
            label: "Kuttanad",
          },
          {
            value: "Ambalappuzha",
            label: "Ambalappuzha",
          },
          {
            value: "Cherthala",
            label: "Cherthala",
          },
        ],
      },
      {
        id: 279,
        name: "Ernakulam",
        state_id: 13,
        children: [
          {
            value: "Kothamangalam",
            label: "Kothamangalam",
          },
          {
            value: "Muvattupuzha",
            label: "Muvattupuzha",
          },
          {
            value: "Kunnathunad",
            label: "Kunnathunad",
          },
          {
            value: "Kanayannur",
            label: "Kanayannur",
          },
          {
            value: "Kochi",
            label: "Kochi",
          },
          {
            value: "North Paravur",
            label: "North Paravur",
          },
          {
            value: "Aluva",
            label: "Aluva",
          },
        ],
      },
      {
        id: 280,
        name: "Idukki",
        state_id: 13,
        children: [
          {
            value: "Peermade",
            label: "Peermade",
          },
          {
            value: "Udumbanchola",
            label: "Udumbanchola",
          },
          {
            value: "Idukki",
            label: "Idukki",
          },
          {
            value: "Thodupuzha",
            label: "Thodupuzha",
          },
          {
            value: "Devikulam",
            label: "Devikulam",
          },
        ],
      },
      {
        id: 281,
        name: "Kannur",
        state_id: 13,
        children: [
          {
            value: "Thalassery",
            label: "Thalassery",
          },
          {
            value: "Iritty",
            label: "Iritty",
          },
          {
            value: "Kannur",
            label: "Kannur",
          },
          {
            value: "Thaliparamba",
            label: "Thaliparamba",
          },
        ],
      },
      {
        id: 282,
        name: "Kasaragod",
        state_id: 13,
        children: [
          {
            value: "Hosdurg",
            label: "Hosdurg",
          },
          {
            value: "Vellarikundu",
            label: "Vellarikundu",
          },
          {
            value: "Kasaragod",
            label: "Kasaragod",
          },
          {
            value: "Manjeshwaram",
            label: "Manjeshwaram",
          },
        ],
      },
      {
        id: 283,
        name: "Kollam",
        state_id: 13,
        children: [
          {
            value: "Kollam",
            label: "Kollam",
          },
          {
            value: "Kunnathoor",
            label: "Kunnathoor",
          },
          {
            value: "Karunagappally",
            label: "Karunagappally",
          },
          {
            value: "Kottarakkara",
            label: "Kottarakkara",
          },
          {
            value: "Punalur",
            label: "Punalur",
          },
          {
            value: "Pathanapuram",
            label: "Pathanapuram",
          },
        ],
      },
      {
        id: 284,
        name: "Kottayam",
        state_id: 13,
        children: [
          {
            value: "Changanasserry",
            label: "Changanasserry",
          },
          {
            value: "Kottayam",
            label: "Kottayam",
          },
          {
            value: "Vaikom",
            label: "Vaikom",
          },
          {
            value: "Meenachil",
            label: "Meenachil",
          },
          {
            value: "Kanjirappally",
            label: "Kanjirappally",
          },
        ],
      },
      {
        id: 285,
        name: "Kozhikode",
        state_id: 13,
        children: [
          {
            value: "Kozhikode",
            label: "Kozhikode",
          },
          {
            value: "Thamarassery",
            label: "Thamarassery",
          },
          {
            value: "Koyilandy",
            label: "Koyilandy",
          },
          {
            value: "Vatakara",
            label: "Vatakara",
          },
          {
            value: "Vythiri",
            label: "Vythiri",
          },
          {
            value: "Sulthan Bathery",
            label: "Sulthan Bathery",
          },
          {
            value: "Mananthavady",
            label: "Mananthavady",
          },
        ],
      },
      {
        id: 286,
        name: "Malappuram",
        state_id: 13,
        children: [
          {
            value: "Perinthalmanna",
            label: "Perinthalmanna",
          },
          {
            value: "Nilambur",
            label: "Nilambur",
          },
          {
            value: "Eranad",
            label: "Eranad",
          },
          {
            value: "Kondotty",
            label: "Kondotty",
          },
          {
            value: "Ponnani",
            label: "Ponnani",
          },
          {
            value: "Tirur",
            label: "Tirur",
          },
          {
            value: "Tirurangadi",
            label: "Tirurangadi",
          },
        ],
      },
      {
        id: 287,
        name: "Palakkad",
        state_id: 13,
        children: [
          {
            value: "Alathoor",
            label: "Alathoor",
          },
          {
            value: "Chittur",
            label: "Chittur",
          },
          {
            value: "Palakkad",
            label: "Palakkad",
          },
          {
            value: "Pattambi",
            label: "Pattambi",
          },
          {
            value: "Ottappalam",
            label: "Ottappalam",
          },
          {
            value: "Mannarkkad",
            label: "Mannarkkad",
          },
          {
            value: "Attappady",
            label: "Attappady",
          },
        ],
      },
      {
        id: 288,
        name: "Pathanamthitta",
        state_id: 13,
        children: [
          {
            value: "Adoor",
            label: "Adoor",
          },
          {
            value: "Konni",
            label: "Konni",
          },
          {
            value: "Kozhencherry",
            label: "Kozhencherry",
          },
          {
            value: "Ranni",
            label: "Ranni",
          },
          {
            value: "Mallappally",
            label: "Mallappally",
          },
          {
            value: "Thiruvalla",
            label: "Thiruvalla",
          },
        ],
      },
      {
        id: 289,
        name: "Thiruvananthapuram",
        state_id: 13,
        children: [
          {
            value: "Neyyattinkara",
            label: "Neyyattinkara",
          },
          {
            value: "Kattakkada",
            label: "Kattakkada",
          },
          {
            value: "Nedumangadu",
            label: "Nedumangadu",
          },
          {
            value: "Thiruvananthapuram",
            label: "Thiruvananthapuram",
          },
          {
            value: "Chirayinkeezhu",
            label: "Chirayinkeezhu",
          },
          {
            value: "Varkala",
            label: "Varkala",
          },
        ],
      },
      {
        id: 290,
        name: "Thrissur",
        state_id: 13,
        children: [
          {
            value: "Chalakudy",
            label: "Chalakudy",
          },
          {
            value: "Mukundapuram",
            label: "Mukundapuram",
          },
          {
            value: "Kodungallur",
            label: "Kodungallur",
          },
          {
            value: "Thrissur",
            label: "Thrissur",
          },
          {
            value: "Chavakkad",
            label: "Chavakkad",
          },
          {
            value: "Kunnamkulam",
            label: "Kunnamkulam",
          },
          {
            value: "Thalapilly",
            label: "Thalapilly",
          },
        ],
      },
      {
        id: 291,
        name: "Wayanad",
        state_id: 13,
        children: [
          {
            value: "Neyyattinkara",
            label: "Neyyattinkara",
          },
          {
            value: "Kattakkada",
            label: "Kattakkada",
          },
          {
            value: "Nedumangadu",
            label: "Nedumangadu",
          },
          {
            value: "Thiruvananthapuram",
            label: "Thiruvananthapuram",
          },
          {
            value: "Chirayinkeezhu",
            label: "Chirayinkeezhu",
          },
          {
            value: "Varkala",
            label: "Varkala",
          },
        ],
      },
    ],
  },
  {
    id: 14,
    name: "Madhya Pradesh",
    districts: [
      { id: 292, name: "Agar Malwa", state_id: 14 },
      { id: 293, name: "Alirajpur", state_id: 14 },
      { id: 294, name: "Anuppur", state_id: 14 },
      { id: 295, name: "Ashoknagar", state_id: 14 },
      { id: 296, name: "Balaghat", state_id: 14 },
      { id: 297, name: "Barwani", state_id: 14 },
      { id: 298, name: "Betul", state_id: 14 },
      { id: 299, name: "Bhind", state_id: 14 },
      { id: 300, name: "Bhopal", state_id: 14 },
      { id: 301, name: "Burhanpur", state_id: 14 },
      { id: 302, name: "Chhatarpur", state_id: 14 },
      { id: 303, name: "Chhindwara", state_id: 14 },
      { id: 304, name: "Damoh", state_id: 14 },
      { id: 305, name: "Datia", state_id: 14 },
      { id: 306, name: "Dewas", state_id: 14 },
      { id: 307, name: "Dhar", state_id: 14 },
      { id: 308, name: "Dindori", state_id: 14 },
      { id: 309, name: "Guna", state_id: 14 },
      { id: 310, name: "Gwalior", state_id: 14 },
      { id: 311, name: "Harda", state_id: 14 },
      { id: 312, name: "Hoshangabad", state_id: 14 },
      { id: 313, name: "Indore", state_id: 14 },
      { id: 314, name: "Jabalpur", state_id: 14 },
      { id: 315, name: "Jhabua", state_id: 14 },
      { id: 316, name: "Katni", state_id: 14 },
      { id: 317, name: "Khandwa", state_id: 14 },
      { id: 318, name: "Khargone", state_id: 14 },
      { id: 319, name: "Mandla", state_id: 14 },
      { id: 320, name: "Mandsaur", state_id: 14 },
      { id: 321, name: "Morena", state_id: 14 },
      { id: 322, name: "Narsinghpur", state_id: 14 },
      { id: 323, name: "Neemuch", state_id: 14 },
      { id: 324, name: "Panna", state_id: 14 },
      { id: 325, name: "Raisen", state_id: 14 },
      { id: 326, name: "Rajgarh", state_id: 14 },
      { id: 327, name: "Ratlam", state_id: 14 },
      { id: 328, name: "Rewa", state_id: 14 },
      { id: 329, name: "Sagar", state_id: 14 },
      { id: 330, name: "Satna", state_id: 14 },
      { id: 331, name: "Sehore", state_id: 14 },
      { id: 332, name: "Seoni", state_id: 14 },
      { id: 333, name: "Shahdol", state_id: 14 },
      { id: 334, name: "Shajapur", state_id: 14 },
      { id: 335, name: "Sheopur", state_id: 14 },
      { id: 336, name: "Shivpuri", state_id: 14 },
      { id: 337, name: "Sidhi", state_id: 14 },
      { id: 338, name: "Singrauli", state_id: 14 },
      { id: 339, name: "Tikamgarh", state_id: 14 },
      { id: 340, name: "Ujjain", state_id: 14 },
      { id: 341, name: "Umaria", state_id: 14 },
      { id: 342, name: "Vidisha", state_id: 14 },
    ],
  },
  {
    id: 15,
    name: "Maharashtra",
    districts: [
      { id: 343, name: "Ahmednagar", state_id: 15 },
      { id: 344, name: "Akola", state_id: 15 },
      { id: 345, name: "Amravati", state_id: 15 },
      { id: 346, name: "Aurangabad", state_id: 15 },
      { id: 347, name: "Beed", state_id: 15 },
      { id: 348, name: "Bhandara", state_id: 15 },
      { id: 349, name: "Buldhana", state_id: 15 },
      { id: 350, name: "Chandrapur", state_id: 15 },
      { id: 351, name: "Dhule", state_id: 15 },
      { id: 352, name: "Gadchiroli", state_id: 15 },
      { id: 353, name: "Gondia", state_id: 15 },
      { id: 354, name: "Hingoli", state_id: 15 },
      { id: 355, name: "Jalgaon", state_id: 15 },
      { id: 356, name: "Jalna", state_id: 15 },
      { id: 357, name: "Kolhapur", state_id: 15 },
      { id: 358, name: "Latur", state_id: 15 },
      { id: 359, name: "Mumbai City", state_id: 15 },
      { id: 360, name: "Mumbai Suburban", state_id: 15 },
      { id: 361, name: "Nagpur", state_id: 15 },
      { id: 362, name: "Nanded", state_id: 15 },
      { id: 363, name: "Nandurbar", state_id: 15 },
      { id: 364, name: "Nashik", state_id: 15 },
      { id: 365, name: "Osmanabad", state_id: 15 },
      { id: 366, name: "Palghar", state_id: 15 },
      { id: 367, name: "Parbhani", state_id: 15 },
      { id: 368, name: "Pune", state_id: 15 },
      { id: 369, name: "Raigad", state_id: 15 },
      { id: 370, name: "Ratnagiri", state_id: 15 },
      { id: 371, name: "Sangli", state_id: 15 },
      { id: 372, name: "Satara", state_id: 15 },
      { id: 373, name: "Sindhudurg", state_id: 15 },
      { id: 374, name: "Solapur", state_id: 15 },
      { id: 375, name: "Thane", state_id: 15 },
      { id: 376, name: "Wardha", state_id: 15 },
      { id: 377, name: "Washim", state_id: 15 },
      { id: 378, name: "Yavatmal", state_id: 15 },
    ],
  },
  {
    id: 16,
    name: "Manipur",
    districts: [
      { id: 379, name: "Bishnupur", state_id: 16 },
      { id: 380, name: "Chandel", state_id: 16 },
      { id: 381, name: "Churachandpur", state_id: 16 },
      { id: 382, name: "Imphal East", state_id: 16 },
      { id: 383, name: "Imphal West", state_id: 16 },
      { id: 384, name: "Jiribam", state_id: 16 },
      { id: 385, name: "Kakching", state_id: 16 },
      { id: 386, name: "Kamjong", state_id: 16 },
      { id: 387, name: "Kangpokpi", state_id: 16 },
      { id: 388, name: "Noney", state_id: 16 },
      { id: 389, name: "Pherzawl", state_id: 16 },
      { id: 390, name: "Senapati", state_id: 16 },
      { id: 391, name: "Tamenglong", state_id: 16 },
      { id: 392, name: "Tengnoupal", state_id: 16 },
      { id: 393, name: "Thoubal", state_id: 16 },
      { id: 394, name: "Ukhrul", state_id: 16 },
    ],
  },
  {
    id: 17,
    name: "Meghalaya",
    districts: [
      { id: 395, name: "East Garo Hills", state_id: 17 },
      { id: 396, name: "East Jaintia Hills", state_id: 17 },
      { id: 397, name: "East Khasi Hills", state_id: 17 },
      { id: 398, name: "North Garo Hills", state_id: 17 },
      { id: 399, name: "Ri Bhoi", state_id: 17 },
      { id: 400, name: "South Garo Hills", state_id: 17 },
      { id: 401, name: "South West Garo Hills ", state_id: 17 },
      { id: 402, name: "South West Khasi Hills", state_id: 17 },
      { id: 403, name: "West Garo Hills", state_id: 17 },
      { id: 404, name: "West Jaintia Hills", state_id: 17 },
      { id: 405, name: "West Khasi Hills", state_id: 17 },
    ],
  },
  {
    id: 18,
    name: "Mizoram",
    districts: [
      { id: 406, name: "Aizawl", state_id: 18 },
      { id: 407, name: "Champhai", state_id: 18 },
      { id: 408, name: "Kolasib", state_id: 18 },
      { id: 409, name: "Lawngtlai", state_id: 18 },
      { id: 410, name: "Lunglei", state_id: 18 },
      { id: 411, name: "Mamit", state_id: 18 },
      { id: 412, name: "Saiha", state_id: 18 },
      { id: 413, name: "Serchhip", state_id: 18 },
    ],
  },
  {
    id: 19,
    name: "Nagaland",
    districts: [
      { id: 414, name: "Dimapur", state_id: 19 },
      { id: 415, name: "Kiphire", state_id: 19 },
      { id: 416, name: "Kohima", state_id: 19 },
      { id: 417, name: "Longleng", state_id: 19 },
      { id: 418, name: "Mokokchung", state_id: 19 },
      { id: 419, name: "Mon", state_id: 19 },
      { id: 420, name: "Peren", state_id: 19 },
      { id: 421, name: "Phek", state_id: 19 },
      { id: 422, name: "Tuensang", state_id: 19 },
      { id: 423, name: "Wokha", state_id: 19 },
      { id: 424, name: "Zunheboto", state_id: 19 },
    ],
  },
  {
    id: 20,
    name: "Odisha",
    districts: [
      { id: 425, name: "Angul", state_id: 20 },
      { id: 426, name: "Balangir", state_id: 20 },
      { id: 427, name: "Balasore", state_id: 20 },
      { id: 428, name: "Bargarh", state_id: 20 },
      { id: 429, name: "Bhadrak", state_id: 20 },
      { id: 430, name: "Boudh", state_id: 20 },
      { id: 431, name: "Cuttack", state_id: 20 },
      { id: 432, name: "Deogarh", state_id: 20 },
      { id: 433, name: "Dhenkanal", state_id: 20 },
      { id: 434, name: "Gajapati", state_id: 20 },
      { id: 435, name: "Ganjam", state_id: 20 },
      { id: 436, name: "Jagatsinghapur", state_id: 20 },
      { id: 437, name: "Jajpur", state_id: 20 },
      { id: 438, name: "Jharsuguda", state_id: 20 },
      { id: 439, name: "Kalahandi", state_id: 20 },
      { id: 440, name: "Kandhamal", state_id: 20 },
      { id: 441, name: "Kendrapara", state_id: 20 },
      { id: 442, name: "Kendujhar (Keonjhar)", state_id: 20 },
      { id: 443, name: "Khordha", state_id: 20 },
      { id: 444, name: "Koraput", state_id: 20 },
      { id: 445, name: "Malkangiri", state_id: 20 },
      { id: 446, name: "Mayurbhanj", state_id: 20 },
      { id: 447, name: "Nabarangpur", state_id: 20 },
      { id: 448, name: "Nayagarh", state_id: 20 },
      { id: 449, name: "Nuapada", state_id: 20 },
      { id: 450, name: "Puri", state_id: 20 },
      { id: 451, name: "Rayagada", state_id: 20 },
      { id: 452, name: "Sambalpur", state_id: 20 },
      { id: 453, name: "Sonepur", state_id: 20 },
      { id: 454, name: "Sundargarh", state_id: 20 },
    ],
  },
  {
    id: 21,
    name: "Punjab",
    districts: [
      { id: 455, name: "Amritsar", state_id: 21 },
      { id: 456, name: "Barnala", state_id: 21 },
      { id: 457, name: "Bathinda", state_id: 21 },
      { id: 458, name: "Faridkot", state_id: 21 },
      { id: 459, name: "Fatehgarh Sahib", state_id: 21 },
      { id: 460, name: "Fazilka", state_id: 21 },
      { id: 461, name: "Ferozepur", state_id: 21 },
      { id: 462, name: "Gurdaspur", state_id: 21 },
      { id: 463, name: "Hoshiarpur", state_id: 21 },
      { id: 464, name: "Jalandhar", state_id: 21 },
      { id: 465, name: "Kapurthala", state_id: 21 },
      { id: 466, name: "Ludhiana", state_id: 21 },
      { id: 467, name: "Mansa", state_id: 21 },
      { id: 468, name: "Moga", state_id: 21 },
      { id: 469, name: "Muktsar", state_id: 21 },
      {
        id: 470,
        name: "Nawanshahr (Shahid Bhagat Singh Nagar)",
        state_id: 21,
      },
      { id: 471, name: "Pathankot", state_id: 21 },
      { id: 472, name: "Patiala", state_id: 21 },
      { id: 473, name: "Rupnagar", state_id: 21 },
      {
        id: 474,
        name: "Sahibzada Ajit Singh Nagar (Mohali)",
        state_id: 21,
      },
      { id: 475, name: "Sangrur", state_id: 21 },
      { id: 476, name: "Tarn Taran", state_id: 21 },
    ],
  },
  {
    id: 22,
    name: "Rajasthan",
    districts: [
      { id: 477, name: "Ajmer", state_id: 22 },
      { id: 478, name: "Alwar", state_id: 22 },
      { id: 479, name: "Banswara", state_id: 22 },
      { id: 480, name: "Baran", state_id: 22 },
      { id: 481, name: "Barmer", state_id: 22 },
      { id: 482, name: "Bharatpur", state_id: 22 },
      { id: 483, name: "Bhilwara", state_id: 22 },
      { id: 484, name: "Bikaner", state_id: 22 },
      { id: 485, name: "Bundi", state_id: 22 },
      { id: 486, name: "Chittorgarh", state_id: 22 },
      { id: 487, name: "Churu", state_id: 22 },
      { id: 488, name: "Dausa", state_id: 22 },
      { id: 489, name: "Dholpur", state_id: 22 },
      { id: 490, name: "Dungarpur", state_id: 22 },
      { id: 491, name: "Hanumangarh", state_id: 22 },
      { id: 492, name: "Jaipur", state_id: 22 },
      { id: 493, name: "Jaisalmer", state_id: 22 },
      { id: 494, name: "Jalore", state_id: 22 },
      { id: 495, name: "Jhalawar", state_id: 22 },
      { id: 496, name: "Jhunjhunu", state_id: 22 },
      { id: 497, name: "Jodhpur", state_id: 22 },
      { id: 498, name: "Karauli", state_id: 22 },
      { id: 499, name: "Kota", state_id: 22 },
      { id: 500, name: "Nagaur", state_id: 22 },
      { id: 501, name: "Pali", state_id: 22 },
      { id: 502, name: "Pratapgarh", state_id: 22 },
      { id: 503, name: "Rajsamand", state_id: 22 },
      { id: 504, name: "Sawai Madhopur", state_id: 22 },
      { id: 505, name: "Sikar", state_id: 22 },
      { id: 506, name: "Sirohi", state_id: 22 },
      { id: 507, name: "Sri Ganganagar", state_id: 22 },
      { id: 508, name: "Tonk", state_id: 22 },
      { id: 509, name: "Udaipur", state_id: 22 },
    ],
  },
  {
    id: 23,
    name: "Sikkim",
    districts: [
      { id: 510, name: "East Sikkim", state_id: 23 },
      { id: 511, name: "North Sikkim", state_id: 23 },
      { id: 512, name: "South Sikkim", state_id: 23 },
      { id: 513, name: "West Sikkim", state_id: 23 },
    ],
  },
  {
    id: 24,
    name: "Tamil Nadu",
    districts: [
      { id: 514, name: "Ariyalur", state_id: 24 },
      { id: 515, name: "Chennai", state_id: 24 },
      { id: 516, name: "Coimbatore", state_id: 24 },
      { id: 517, name: "Cuddalore", state_id: 24 },
      { id: 518, name: "Dharmapuri", state_id: 24 },
      { id: 519, name: "Dindigul", state_id: 24 },
      { id: 520, name: "Erode", state_id: 24 },
      { id: 521, name: "Kanchipuram", state_id: 24 },
      { id: 522, name: "Kanyakumari", state_id: 24 },
      { id: 523, name: "Karur", state_id: 24 },
      { id: 524, name: "Krishnagiri", state_id: 24 },
      { id: 525, name: "Madurai", state_id: 24 },
      { id: 526, name: "Nagapattinam", state_id: 24 },
      { id: 527, name: "Namakkal", state_id: 24 },
      { id: 528, name: "Nilgiris", state_id: 24 },
      { id: 529, name: "Perambalur", state_id: 24 },
      { id: 530, name: "Pudukkottai", state_id: 24 },
      { id: 531, name: "Ramanathapuram", state_id: 24 },
      { id: 532, name: "Salem", state_id: 24 },
      { id: 533, name: "Sivaganga", state_id: 24 },
      { id: 534, name: "Thanjavur", state_id: 24 },
      { id: 535, name: "Theni", state_id: 24 },
      { id: 536, name: "Thoothukudi (Tuticorin)", state_id: 24 },
      { id: 537, name: "Tiruchirappalli", state_id: 24 },
      { id: 538, name: "Tirunelveli", state_id: 24 },
      { id: 539, name: "Tiruppur", state_id: 24 },
      { id: 540, name: "Tiruvallur", state_id: 24 },
      { id: 541, name: "Tiruvannamalai", state_id: 24 },
      { id: 542, name: "Tiruvarur", state_id: 24 },
      { id: 543, name: "Vellore", state_id: 24 },
      { id: 544, name: "Viluppuram", state_id: 24 },
      { id: 545, name: "Virudhunagar", state_id: 24 },
    ],
  },
  {
    id: 25,
    name: "Telangana",
    districts: [
      { id: 546, name: "Adilabad", state_id: 25 },
      { id: 547, name: "Bhadradri Kothagudem", state_id: 25 },
      { id: 548, name: "Hyderabad", state_id: 25 },
      { id: 549, name: "Jagtial", state_id: 25 },
      { id: 550, name: "Jangaon", state_id: 25 },
      { id: 551, name: "Jayashankar Bhoopalpally", state_id: 25 },
      { id: 552, name: "Jogulamba Gadwal", state_id: 25 },
      { id: 553, name: "Kamareddy", state_id: 25 },
      { id: 554, name: "Karimnagar", state_id: 25 },
      { id: 555, name: "Khammam", state_id: 25 },
      { id: 556, name: "Komaram Bheem Asifabad", state_id: 25 },
      { id: 557, name: "Mahabubabad", state_id: 25 },
      { id: 558, name: "Mahabubnagar", state_id: 25 },
      { id: 559, name: "Mancherial", state_id: 25 },
      { id: 560, name: "Medak", state_id: 25 },
      { id: 561, name: "Medchal", state_id: 25 },
      { id: 562, name: "Nagarkurnool", state_id: 25 },
      { id: 563, name: "Nalgonda", state_id: 25 },
      { id: 564, name: "Nirmal", state_id: 25 },
      { id: 565, name: "Nizamabad", state_id: 25 },
      { id: 566, name: "Peddapalli", state_id: 25 },
      { id: 567, name: "Rajanna Sircilla", state_id: 25 },
      { id: 568, name: "Rangareddy", state_id: 25 },
      { id: 569, name: "Sangareddy", state_id: 25 },
      { id: 570, name: "Siddipet", state_id: 25 },
      { id: 571, name: "Suryapet", state_id: 25 },
      { id: 572, name: "Vikarabad", state_id: 25 },
      { id: 573, name: "Wanaparthy", state_id: 25 },
      { id: 574, name: "Warangal (Rural)", state_id: 25 },
      { id: 575, name: "Warangal (Urban)", state_id: 25 },
      { id: 576, name: "Yadadri Bhuvanagiri", state_id: 25 },
    ],
  },
  {
    id: 26,
    name: "Tripura",
    districts: [
      { id: 577, name: "Dhalai", state_id: 26 },
      { id: 578, name: "Gomati", state_id: 26 },
      { id: 579, name: "Khowai", state_id: 26 },
      { id: 580, name: "North Tripura", state_id: 26 },
      { id: 581, name: "Sepahijala", state_id: 26 },
      { id: 582, name: "South Tripura", state_id: 26 },
      { id: 583, name: "Unakoti", state_id: 26 },
      { id: 584, name: "West Tripura", state_id: 26 },
    ],
  },
  {
    id: 27,
    name: "Uttarakhand",
    districts: [
      { id: 585, name: "Almora", state_id: 27 },
      { id: 586, name: "Bageshwar", state_id: 27 },
      { id: 587, name: "Chamoli", state_id: 27 },
      { id: 588, name: "Champawat", state_id: 27 },
      { id: 589, name: "Dehradun", state_id: 27 },
      { id: 590, name: "Haridwar", state_id: 27 },
      { id: 591, name: "Nainital", state_id: 27 },
      { id: 592, name: "Pauri Garhwal", state_id: 27 },
      { id: 593, name: "Pithoragarh", state_id: 27 },
      { id: 594, name: "Rudraprayag", state_id: 27 },
      { id: 595, name: "Tehri Garhwal", state_id: 27 },
      { id: 596, name: "Udham Singh Nagar", state_id: 27 },
      { id: 597, name: "Uttarkashi", state_id: 27 },
    ],
  },
  {
    id: 28,
    name: "Uttar Pradesh",
    districts: [
      { id: 598, name: "Almora", state_id: 28 },
      { id: 599, name: "Bageshwar", state_id: 28 },
      { id: 600, name: "Chamoli", state_id: 28 },
      { id: 601, name: "Champawat", state_id: 28 },
      { id: 602, name: "Dehradun", state_id: 28 },
      { id: 603, name: "Haridwar", state_id: 28 },
      { id: 604, name: "Nainital", state_id: 28 },
      { id: 605, name: "Pauri Garhwal", state_id: 28 },
      { id: 606, name: "Pithoragarh", state_id: 28 },
      { id: 607, name: "Rudraprayag", state_id: 28 },
      { id: 608, name: "Tehri Garhwal", state_id: 28 },
      { id: 609, name: "Udham Singh Nagar", state_id: 28 },
      { id: 610, name: "Uttarkashi", state_id: 28 },
    ],
  },
  {
    id: 29,
    name: "West Bengal",
    districts: [
      { id: 611, name: "Alipurduar", state_id: 29 },
      { id: 612, name: "Bankura", state_id: 29 },
      { id: 613, name: "Birbhum", state_id: 29 },
      { id: 614, name: "Cooch Behar", state_id: 29 },
      {
        id: 615,
        name: "Dakshin Dinajpur (South Dinajpur)",
        state_id: 29,
      },
      { id: 616, name: "Darjeeling", state_id: 29 },
      { id: 617, name: "Hooghly", state_id: 29 },
      { id: 618, name: "Howrah", state_id: 29 },
      { id: 619, name: "Jalpaiguri", state_id: 29 },
      { id: 620, name: "Jhargram", state_id: 29 },
      { id: 621, name: "Kalimpong", state_id: 29 },
      { id: 622, name: "Kolkata", state_id: 29 },
      { id: 623, name: "Malda", state_id: 29 },
      { id: 624, name: "Murshidabad", state_id: 29 },
      { id: 625, name: "Nadia", state_id: 29 },
      { id: 626, name: "North 24 Parganas", state_id: 29 },
      {
        id: 627,
        name: "Paschim Medinipur (West Medinipur)",
        state_id: 29,
      },
      {
        id: 628,
        name: "Paschim (West) Burdwan (Bardhaman)",
        state_id: 29,
      },
      { id: 629, name: "Purba Burdwan (Bardhaman)", state_id: 29 },
      { id: 630, name: "Purba Medinipur (East Medinipur)", state_id: 29 },
      { id: 631, name: "Purulia", state_id: 29 },
      { id: 632, name: "South 24 Parganas", state_id: 29 },
      { id: 633, name: "Uttar Dinajpur (North Dinajpur)", state_id: 29 },
    ],
  },
  {
    id: 30,
    name: "Andaman and Nicobar Islands",
    districts: [
      { id: 634, name: "Nicobar", state_id: 30 },
      { id: 635, name: "North and Middle Andaman", state_id: 30 },
      { id: 636, name: "South Andaman", state_id: 30 },
    ],
  },
  {
    id: 31,
    name: "Chandigarh",
    districts: [{ id: 637, name: "Chandigarh", state_id: 31 }],
  },
  {
    id: 32,
    name: "Dadra and Nagar Haveli",
    districts: [{ id: 638, name: "Dadra & Nagar Haveli", state_id: 32 }],
  },
  {
    id: 33,
    name: "Daman and Diu",
    districts: [
      { id: 639, name: "Daman", state_id: 33 },
      { id: 640, name: "Diu", state_id: 33 },
    ],
  },
  {
    id: 34,
    name: "Delhi",
    districts: [
      { id: 641, name: "Central Delhi", state_id: 34 },
      { id: 642, name: "East Delhi", state_id: 34 },
      { id: 643, name: "New Delhi", state_id: 34 },
      { id: 644, name: "North Delhi", state_id: 34 },
      { id: 645, name: "North East Delhi", state_id: 34 },
      { id: 646, name: "North West Delhi", state_id: 34 },
      { id: 647, name: "Shahdara", state_id: 34 },
      { id: 648, name: "South Delhi", state_id: 34 },
      { id: 649, name: "South East Delhi", state_id: 34 },
      { id: 650, name: "South West Delhi", state_id: 34 },
      { id: 651, name: "West Delhi", state_id: 34 },
    ],
  },
  {
    id: 35,
    name: "Lakshadweep",
    districts: [{ id: 652, name: "Lakshadweep", state_id: 35 }],
  },
  {
    id: 36,
    name: "Puducherry",
    districts: [
      { id: 653, name: "Karaikal", state_id: 36 },
      { id: 654, name: "Mahe", state_id: 36 },
      { id: 655, name: "Pondicherry", state_id: 36 },
      { id: 656, name: "Yanam", state_id: 36 },
    ],
  },
];

export const states = data.map((state) => {
  const children = state.districts.map((district) => {
    const temp = { ...district, value: district.name, label: district.name };

    delete temp.name;
    delete temp.id;
    delete temp.state_id;

    return temp;
  });

  const temp = {
    ...state,
    value: state.name,
    label: state.name,
    children,
  };

  delete temp.districts;
  delete temp.name;
  delete temp.id;

  return temp;
});
